### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by sxflynn** [SWHL/VideoOCR#3]
This is the error I get in the Terminal.app when I run the code pip install /Users/*******/Downloads/rapidocr-1.0.0-py3-none-any.whl

```
Processing ./Downloads/rapidocr-1.0.0-py3-none-any.whl
Collecting Shapely==1.7.1
  Using cached Shapely-1.7.1.tar.gz (383 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/setup.py'"'"'; __file__='"'"'/private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-pip-egg-info-inozfapk
       cwd: /private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/
  Complete output (12 lines):
  Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
  Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
  Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/setup.py", line 85, in <module>
      from shapely._buildcfg import geos_version_string, geos_version, \
    File "/private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/shapely/_buildcfg.py", line 190, in <module>
      lgeos = load_dll('geos_c', fallbacks=alt_paths)
    File "/private/var/folders/lf/05rwnwxs5n5f8pj438g9ts780000gn/T/pip-install-a03r8vsg/shapely_6a0c11476e6a42bca8be3537bede5cb2/shapely/_buildcfg.py", line 162, in load_dll
      raise OSError(
  OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/42/f3/0e1bc2c4f15e05e30c6b99322b9ddaa2babb3f43bc7df2698efdc1553439/Shapely-1.7.1.tar.gz#sha256=1641724c1055459a7e2b8bbe47ba25bdc89554582e62aec23cb3f3ca25f9b129 (from https://pypi.org/simple/shapely/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement Shapely==1.7.1 (from rapidocr) (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0, 1.7.1, 1.8a1, 1.8a2, 1.8a3, 1.8rc1, 1.8rc2, 1.8.0)
ERROR: No matching distribution found for Shapely==1.7.1

```

**Comment by SWHL** [comment]
I have fixed the problem, you can try it again with your time.

**Comment by sxflynn** [comment]
I'm getting this error when I try again:

This is the command I entered in the Terminal. 

`pip install https://github.com/RapidAI/RapidOCR/raw/main/release/python_sdk/sdk_rapidocr_v1.0.0/rapidocr-1.0.0-py3-none-any.whl -i https://pypi.douban.com/simple/
`

`Looking in indexes: https://pypi.douban.com/simple/
Collecting rapidocr==1.0.0
  Downloading https://github.com/RapidAI/RapidOCR/raw/main/release/python_sdk/sdk_rapidocr_v1.0.0/rapidocr-1.0.0-py3-none-any.whl (18 kB)
Requirement already satisfied: opencv-python>=4.5.1.48 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from rapidocr==1.0.0) (4.5.4.60)
Collecting six>=1.15.0
  Downloading https://pypi.doubanio.com/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy>=1.19.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from rapidocr==1.0.0) (1.21.4)
ERROR: Could not find a version that satisfies the requirement onnxruntime>=1.7.0 (from rapidocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime>=1.7.0`
